In [1]:
import pandas as pd
import requests

In [2]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
}

R1 = requests.get("https://www.hackerrank.com/rest/contests/ignyte/leaderboard?limit=500", headers=headers).json()
R2 = requests.get("https://www.hackerrank.com/rest/contests/ignyte-r2/leaderboard?limit=500", headers=headers).json()

In [3]:
df1 = pd.DataFrame(R1['models'])[['hacker', 'score']]
df2 = pd.DataFrame(R2['models'])[['hacker', 'score']]

df1['pointsR1'] = df1['score'] / 8000
df2['pointsR2'] = df2['score'] / 2300

df = pd.merge(df1, df2, on='hacker', how='outer')
df.fillna(0, inplace=True)

df['total'] = (df['pointsR1'] * .4 + df['pointsR2'] * .6) * 100
df.drop(columns=['pointsR1', 'pointsR2'], inplace=True)
df.sort_values(by='total', ascending=False, inplace=True)
df.set_index('hacker', inplace=True)

df

                  score_x  score_y      total
hacker
yashp20           5442.86  2300.00  87.214300
monopolize_all    5314.29  2300.00  86.571450
singh211          5928.57  1675.00  73.338502
shrey221          5000.00  1800.00  71.956522
anshuman_40d      5642.86  1675.00  71.909952
nirmanjaiswal031  3142.86  1903.77  65.377865
arpan22           5642.86  1284.68  61.727691
Ny0nx___          5642.86  1278.77  61.573517
devraj6102002     3128.57  1420.75  52.705893
shauryav174       5000.00  1000.00  51.086957
pranjalupadhyay4  5928.57   733.47  48.776850
yashprabhattilo1     0.00  1773.58  46.267304
anglefinder       4542.86   700.00  40.975170
nikhil_kumar0901  3771.43   700.00  37.118020
sid200128            0.00  1303.77  34.011391
vasu211           5428.57     0.00  27.142850
kushagraagarwal6  4400.44     0.00  22.002200
Pandey21          3642.86     0.00  18.214300
shivamkryadv7352  3500.00     0.00  17.500000
kashish22         3242.86     0.00  16.214300
kalpandesharmad3  3048.49     0.00  15.242450
charvi23             0.00   500.00  13.043478
23f1002985        2148.49     0.00  10.742450
sahilpandey12125  2100.00     0.00  10.500000
manjul22          2000.00     0.00  10.000000
whatsbehindit5    2000.00     0.00  10.000000
jaybharambe42     1600.00     0.00   8.000000
sumit191             0.00   300.00   7.826087
rudra221          1500.00     0.00   7.500000
kirti221          1227.27     0.00   6.136350
soumyadeepm_sm     548.49     0.00   2.742450
sambit221          500.00     0.00   2.500000
rupayan105das92    500.00     0.00   2.500000
sumitkumar_offi1   500.00     0.00   2.500000
omgovinds15        500.00     0.00   2.500000
aadarsh0810        287.88     0.00   1.439400